name = "clockwork_schedule"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "A scheduling expansion for the Clockwork library, providing a way to define and manage recurring tasks."
licences = ["MIT"]
repository = { type = "github", user = "renatillas", repo = "clockwork_schedule" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.53.0 and < 2.0.0"
gleam_time = ">= 1.0.0 and < 2.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"
clockwork = ">= 4.0.0 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.2.6 and < 2.0.0"
pprint = ">= 1.0.4 and < 2.0.0"
